### ISSUE TITLE
Not able to reproduce Figure1

### ISSUE THREAD

**Issue by FabienRoger** [EleutherAI/elk#43]
I get this

![image](https://user-images.githubusercontent.com/15524303/217333915-ffd4df8c-ed2c-4208-8a39-318850cb6f69.png)

instead of this

![image](https://user-images.githubusercontent.com/15524303/217333964-a96318e6-8871-4ebd-a598-368cd722dae8.png)

Using this script

https://github.com/EleutherAI/elk/blob/figure1-bug-demo/elk/extensions/additional_plots/figure1_generalization.py

And a model trained using

> python -m elk.train --model unifiedqa-t5-11b --prefix normal --dataset copa --num-data 1000

**Comment by FabienRoger** [comment]
Same problem when training new models. Same problem when using the train set instead of the test set.

**Comment by norabelrose** [comment]
This might be due to us using different (global, not prompt-specific) normalization. Might be interesting to check this now.

**Comment by FabienRoger** [comment]
This is mostly due to this figure being produced using the train dataset. See [this](https://www.alignmentforum.org/posts/bWxNPMy5MhPnQTzKz/what-discovering-latent-knowledge-did-and-did-not-find-4).

**Comment by FabienRoger** [comment]
I did not try this again on this codebase, but I think there's nothing to worry about here, and you can safely close this issue.

**Comment by norabelrose** [comment]
@FabienRoger I'm aware that it was produced on the train dataset, but you said earlier in this issue that the problem persisted even when using the train set. I imagine the remaining discrepancy is due to the non-prompt-specific normalization.

I'm not sure what normalization you used in your experiments in that blog post, but this is a big confounding factor that we've noticed which tends to change a lot of results.

**Comment by FabienRoger** [comment]
My bad. Thanks for the correction.
In the blog post, I used the exact normalization used in the paper (not the one described in the paper).

**Comment by norabelrose** [comment]
@FabienRoger Well, it actually matters whether you _separately_ normalize each prompt template, or normalize all prompt templates together. That's a detail that they don't talk about in the paper.

**Comment by FabienRoger** [comment]
Surely you want to do normalization per prompt, right? I would guess that the main effect of normalization is to remove the ability of the model to just give you the "yes vs no" feature through something that looks a lot like "[mean difference ablation](https://arxiv.org/pdf/2212.04273.pdf)". But for some prompt it's "yes vs no", and for others it's "positive vs negative", etc.

I would be really surprised if normalization generalized across prompts. (Although it's a bit unclear to me how many features "mean difference ablation" can ablate at once, so maybe it's fine if you have all the prompts in the dataset used to compute normalization?)

But from what you say, I guess that mean difference ablation is not able to remove this feature enough? Or is it more complex? (I know that you're aware of this kind of considerations, and you probably know more about this than I do.)

**Comment by norabelrose** [comment]
> Surely you want to do normalization per prompt, right?
Well, I think it's _now_ clear that you _either_ want to do normalization separately per prompt, _or_ you want to explicitly do concept erasure on both the prompt ID concept and the pseudolabel concept. Doing separate normalization per prompt ID has the downside that you need to _know_ the prompt ID at inference time, which means you can't apply the reporter to any prompts outside the ones that you used when you trained it.

Also, I'm a bit confused about why you think this is so obvious, because this codebase has been using global, non-prompt-specific normalization ever since we corrected the train-test leakage issue early on, and we only realized recently that this mattered. I suppose you branched off into your own codebase at a certain point, and maybe you made the realization independently.

**Comment by FabienRoger** [comment]
To be honest, I hadn't thought about this before you even mentioned the possibility of doing per prompt normalization. If I had thought about this when I was working on normalization, I would have probably pushed for per-prompt normalization.

Thanks for settling down to these kinds of details!

**Comment by norabelrose** [comment]
No problem, I just wish we had realized this earlier 😅
